version: "3.1"

services:
  games-mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - games-data:/var/data/mongo

  games-cassandra:
    image: cassandra
    restart: always
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
    volumes:
      - activity-tracking-data:/var/data/cassandra
  
volumes:
  games-data:
  activity-tracking-data:
